required_plugins = %w( vagrant-proxyconf vagrant-cachier )
required_plugins.each do |plugin|
  system "vagrant plugin install #{plugin}" unless Vagrant.has_plugin? plugin
end

Vagrant.configure('2') do |config|
  config.vm.box = 'centos-6.6-preheated'
  config.ssh.insert_key = false
  config.vm.network 'private_network', ip: '172.19.19.19'
  config.vm.provision 'shell', path: 'scripts/provision.sh'
end
